### ISSUE TITLE
regex_error when calling npy_load

### ISSUE THREAD

**Issue by eugenelyj** [rogersce/cnpy#61]
I met a problem when running example program. Does anyone met similar problem before? Looking forward to any comments.
The following are details:

Platform: Centos 7.2.1511
g++: 4.8.5
```
terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
```

BackTrace

```
#0  0x00007ffff6d5e5f7 in raise () from /usr/lib64/libc.so.6
#1  0x00007ffff6d5fce8 in abort () from /usr/lib64/libc.so.6
#2  0x00007ffff76908bd in __gnu_cxx::__verbose_terminate_handler ()
    at ../../.././libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff768e906 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff768e951 in std::terminate () at ../../.././libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff768eb68 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x62e120, 
    tinfo=0x7ffff7970b70 <typeinfo for std::regex_error>, 
    dest=0x7ffff76b7ca0 <std::regex_error::~regex_error()>)
    at ../../.././libstdc++-v3/libsupc++/eh_throw.cc:87
---Type <return> to continue, or q <return> to quit---
#6  0x00007ffff76b6765 in std::__throw_regex_error (__ecode=std::regex_constants::_S_error_brack)
    at ../../../.././libstdc++-v3/src/c++11/functexcept.cc:144
#7  0x00007ffff7bcc374 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_bracket_expression (this=0x7fffffffd8b0) at /usr/include/c++/4.8.2/bits/regex_compiler.h:974
#8  0x00007ffff7bcb1d1 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_atom (
    this=0x7fffffffd8b0) at /usr/include/c++/4.8.2/bits/regex_compiler.h:960
#9  0x00007ffff7bc9cb3 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_term (
    this=0x7fffffffd8b0) at /usr/include/c++/4.8.2/bits/regex_compiler.h:795
#10 0x00007ffff7bc823e in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_alternative (
    this=0x7fffffffd8b0) at /usr/include/c++/4.8.2/bits/regex_compiler.h:773
#11 0x00007ffff7bc6a4c in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_M_disjunction (
---Type <return> to continue, or q <return> to quit---
    this=0x7fffffffd8b0) at /usr/include/c++/4.8.2/bits/regex_compiler.h:758
#12 0x00007ffff7bc4c54 in std::__detail::_Compiler<char const*, std::regex_traits<char> >::_Compiler (
    this=0x7fffffffd8b0, __b=@0x7fffffffd9b0: 0x7ffff7bce05f "[0-9][0-9]*", 
    __e=@0x7fffffffd9c8: 0x7ffff7bce06a "", __traits=..., __flags=16)
    at /usr/include/c++/4.8.2/bits/regex_compiler.h:729
#13 0x00007ffff7bc2cfe in std::__detail::__compile<char const*, std::regex_traits<char> > (
    __b=@0x7fffffffd9b0: 0x7ffff7bce05f "[0-9][0-9]*", __e=@0x7fffffffd9c8: 0x7ffff7bce06a "", __t=..., 
    __f=16) at /usr/include/c++/4.8.2/bits/regex_compiler.h:1105
#14 0x00007ffff7bc1473 in std::basic_regex<char, std::regex_traits<char> >::basic_regex (
    this=0x7fffffffda20, __p=0x7ffff7bce05f "[0-9][0-9]*", __f=16)
    at /usr/include/c++/4.8.2/bits/regex.h:388
---Type <return> to continue, or q <return> to quit---
#15 0x00007ffff7bbda36 in cnpy::parse_npy_header (fp=0x62dca0, word_size=@0x7fffffffdc78: 6479008, 
    shape=..., fortran_order=@0x7fffffffdc77: false)
    at /path/to/3rdparty/cnpy/cnpy.cpp:127
#16 0x00007ffff7bbe21c in load_the_npy_file (fp=0x62dca0)
    at /path/to/3rdparty/cnpy/cnpy.cpp:182
#17 0x00007ffff7bbf6cd in cnpy::npy_load (fname=...)
    at /path/to/3rdparty/cnpy/cnpy.cpp:333
#18 0x000000000040d45e in main ()
    at /path/to/3rdparty/cnpy/example1.cpp:24
```

**Comment by eugenelyj** [comment]
It seems the g++ version is too low. After i set it to g++7, the problem was solved.
